/*
 * 
 * SendGrid Design Tokens
 * 
 */

module.exports = {
  borderRadius: "2px",
  colfax: "\"Colfax\", Helvetica, Arial, sans-serif",
  colfaxBold: "\"Colfax-Bold\", Helvetica, Arial, sans-serif",
  colfaxLight: "\"Colfax-Light\", Helvetica, Arial, sans-serif",
  colfaxMedium: "\"Colfax-Medium\", Helvetica, Arial, sans-serif",
  colorAlertDanger: "#f4dddd",
  colorAlertDangerText: "#b71c1c",
  colorAlertSuccess: "#f1f7e9",
  colorAlertSuccessText: "#2e6b30",
  colorAlertTrial: "#294661",
  colorAlertVerification: "#18c96e",
  colorAlertWarning: "#fefae6",
  colorAlertWarningText: "#8c6c15",
  colorBlack: "#000",
  colorBlue: "#1a82e2",
  colorBlue02: "#fbfdff",
  colorBlue05: "#f3f9fd",
  colorBlue10: "#e8f2fc",
  colorBlue20: "#d1e6f9",
  colorBlue40: "#a3cdf3",
  colorBlue60: "#76b4ee",
  colorBlue80: "#489be8",
  colorBluebird: "#2196f3",
  colorBurntOrange: "#ff5722",
  colorCaribbean: "#00e5ff",
  colorCarrot: "#f90",
  colorCobalt: "#303f9f",
  colorCrown: "#7b1fa2",
  colorGrassStain: "#8ac24a",
  colorHighlighter: "rgba(#fdd835, 0.6)",
  colorLavender: "#dea7e8",
  colorLime: "#cbdb39",
  colorLogoAccentDark: "#009dd9",
  colorLogoAccentLight: "#99e1f4",
  colorLogoAccentMedium: "#00b3e3",
  colorMango: "#fdd835",
  colorMantis: "#18c96e",
  colorRonBurgundy: "#b71c1c",
  colorSangria: "#880e4f",
  colorScreample: "#7c4dff",
  colorSeafoam: "#00bcd4",
  colorSlate: "#294661",
  colorSlate02: "#fbfbfc",
  colorSlate05: "#f4f6f7",
  colorSlate10: "#e9ecef",
  colorSlate20: "#d4dadf",
  colorSlate40: "#a9b5c0",
  colorSlate60: "#7f90a0",
  colorSlate80: "#546b81",
  colorSlateDark05: "#16452d",
  colorSpruce: "#4cb04f",
  colorSteel: "#9e9e9e",
  colorWhite: "#fff",
  colorWildStrawberry: "#ff4081",
  compareBorderColor: "#e9ecef",
  divBorderColor: "#e9ecef",
  divBorderColorDark: "#d4dadf",
  divBorderDashed: "dashed",
  divBorderRadius: "2px",
  divBorderSolid: "solid",
  divBorderWidth: "1px",
  dropdownMenuZIndex: "1000",
  dropzoneBg: "#fbfbfc",
  dropzoneBgActive: "#f4f6f7",
  dropzoneBorderActive: "#7f90a0",
  dropzoneHoveredBg: "#e7f9f0",
  dropzoneHoveredBorder: "#18c96e",
  fontPath: "\"../fonts\"",
  headerTabsBorderColor: "rgba(#000, 0.2)",
  headerTabsHover: "#394f64",
  iconAirplane: "\"\e90b\"",
  iconAirplaneFill: "\"\e912\"",
  iconAlignCenter: "\"\e927\"",
  iconAlignLeft: "\"\e928\"",
  iconAlignRight: "\"\e929\"",
  iconAnalytics: "\"\e915\"",
  iconAutomation: "\"\e939\"",
  iconBuilder: "\"\e914\"",
  iconButton: "\"\e920\"",
  iconCalendar: "\"\e917\"",
  iconCaret: "\"\e900\"",
  iconCheck: "\"\e905\"",
  iconCheckCircle: "\"\e907\"",
  iconCheckShield: "\"\e93f\"",
  iconCheckThin: "\"\e938\"",
  iconCleanUi: "\"\e916\"",
  iconClick: "\"\e93b\"",
  iconClock: "\"\e90d\"",
  iconCloudQuestion: "\"\e93c\"",
  iconCode: "\"\e919\"",
  iconColumnFour: "\"\e950\"",
  iconColumnOne: "\"\e953\"",
  iconColumnThree: "\"\e951\"",
  iconColumnTwo: "\"\e952\"",
  iconColumns: "\"\e923\"",
  iconContacts: "\"\e913\"",
  iconContactsAlt: "\"\e92c\"",
  iconCopy: "\"\e902\"",
  iconCreate: "\"\e901\"",
  iconCsv: "\"\e92a\"",
  iconDesktopView: "\"\e627\"",
  iconDivider: "\"\e91a\"",
  iconDownload: "\"\e93e\"",
  iconDrag: "\"\e91b\"",
  iconEditorCode: "\"\e934\"",
  iconEditorDesign: "\"\e935\"",
  iconEditorOld: "\"\e933\"",
  iconEllipsis: "\"\e90e\"",
  iconEllipsisVertical: "\"\e93a\"",
  iconForms: "\"\e94f\"",
  iconGear: "\"\e608\"",
  iconHelp: "\"\e932\"",
  iconHelpError: "\"\e93d\"",
  iconImage: "\"\e91e\"",
  iconImageText: "\"\e922\"",
  iconImages: "\"\e924\"",
  iconInfoCircle: "\"\e903\"",
  iconKey: "\"\e918\"",
  iconList: "\"\e92b\"",
  iconLocked: "\"\e91d\"",
  iconMail: "\"\e61d\"",
  iconMailSearch: "\"\e92d\"",
  iconMcAlignCenter: "\"\e94d\"",
  iconMcAlignJustify: "\"\e947\"",
  iconMcAlignLeft: "\"\e94e\"",
  iconMcAlignRight: "\"\e94c\"",
  iconMcCode: "\"\e942\"",
  iconMcDesign: "\"\e629\"",
  iconMcFormatBold: "\"\e94b\"",
  iconMcFormatItalic: "\"\e94a\"",
  iconMcFormatLink: "\"\e949\"",
  iconMcFormatUnderline: "\"\e948\"",
  iconMcOrderedList: "\"\e946\"",
  iconMcPreview: "\"\e602\"",
  iconMcReturn: "\"\e615\"",
  iconMcTestData: "\"\e943\"",
  iconMcUnorderedList: "\"\e945\"",
  iconMobileView: "\"\e61c\"",
  iconMoveLeft: "\"\e941\"",
  iconMoveRight: "\"\e940\"",
  iconPencil: "\"\e624\"",
  iconPeople: "\"\e601\"",
  iconPieChart: "\"\e606\"",
  iconPlus: "\"\e617\"",
  iconReload: "\"\e926\"",
  iconSaveDraft: "\"\e911\"",
  iconSearch: "\"\e906\"",
  iconSegment: "\"\e609\"",
  iconSocial: "\"\e925\"",
  iconSortAsc: "\"\e910\"",
  iconSortDesc: "\"\e90f\"",
  iconSpace: "\"\e944\"",
  iconSpacer: "\"\e91f\"",
  iconStatusCaution: "\"\e92f\"",
  iconStatusNegative: "\"\e930\"",
  iconStatusPositive: "\"\e92e\"",
  iconTeammate: "\"\e90c\"",
  iconTestData: "\"\e937\"",
  iconText: "\"\e921\"",
  iconTextOnly: "\"\e603\"",
  iconTrash: "\"\e62b\"",
  iconUnlocked: "\"\e91c\"",
  iconUnsubscribe: "\"\e936\"",
  iconUpload: "\"\e931\"",
  iconUserSecurity: "\"\e90a\"",
  iconView: "\"\e600\"",
  iconWarning: "\"\e909\"",
  iconWarningTriangle: "\"\e904\"",
  iconX: "\"\e908\"",
  iconXLegacy: "\"\e62e\"",
  infoPopupZIndex: "19000",
  loaderDarkLight: "rgba(#fff, 0.35)",
  loaderDarkMedium: "rgba(#fff, 0.75)",
  loaderDarkMediumSolid: "rgba(#fff, 0.9)",
  loaderDarkSolid: "#fff",
  modalBg: "rgba(#000, 0.5)",
  modalBodyHeight: "454px",
  modalCenterBg: "#fff",
  modalCenterPosition: "300px",
  modalCenterWidth: "600px",
  modalFooterHeight: "71px",
  modalHeight: "665px",
  modalSideShadow: "-2px 0 6px rgba(#294661, 0.1)",
  modalWidth: "525px",
  modalZIndex: "20000",
  scaleBase: "12px",
  scaleBaseDown01: "9px",
  scaleBaseDown02: "6px",
  scaleBaseDown03: "3px",
  scaleBaseUp01: "13px",
  scaleBaseUp02: "15px",
  scaleBaseUp03: "18px",
  scaleBaseUp04: "20px",
  scaleBaseUp05: "27px",
  scaleBaseUp06: "30px",
  scaleBaseUp07: "40px",
  scaleBaseUp08: "45px",
  scaleBaseUp09: "60px",
  scaleBaseUp10: "90px",
  segmentTermMaxWidth: "768px",
  selectDisabledColor: "rgba(#9e9e9e, 0.4)",
  select2DisabledArrow: "rgba(#9e9e9e, 0.4)",
  select2DisabledBorder: "rgba(#9e9e9e, 0.4)",
  select2DisabledPlacholder: "rgba(#9e9e9e, 0.4)",
  spacingLg: "30px",
  spacingMd: "20px",
  spacingSm: "12px",
  spacingXl: "45px",
  spacingXs: "9px",
  spacingXxl: "60px",
  spotlightCircleZIndex: "10000",
  spotlightTooltipZIndex: "10010",
  statsClicks: "#7b1fa2",
  statsDelivered: "#8ac24a",
  statsOpens: "#303f9f",
  statsSpamReports: "#b71c1c",
  statsUniqueClicks: "#7c4dff",
  statsUniqueOpens: "#2196f3",
  statsUnsubscribes: "#880e4f",
  switchBackgroundZIndex: "10",
  switchOptionZIndex: "12",
  switchSelectorZIndex: "11",
  textAreaDisabledBorder: "rgba(#9e9e9e, 0.4)",
  textAreaDisabledColor: "rgba(#9e9e9e, 0.4)",
  textInputDisabledBorder: "rgba(#9e9e9e, 0.4)",
  textInputDisabledColor: "rgba(#9e9e9e, 0.4)",
  textInputSearchTitleBg: "rgba(#1a82e2, 0.1)",
  tooltipArrowHeight: "6px",
  tooltipBg: "#294661",
  tooltipFontSize: "12px",
  tooltipLineHeight: "18px"
};